<template>
  <div class="loadingio-spinner-spin-jpeea6upf9"><div class="ldio-4ombiim29sv">
  <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
  </div></div>
</template>



<style type="text/css">
@keyframes ldio-4ombiim29sv {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5,1.5);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.ldio-4ombiim29sv div > div {
  position: absolute;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #2579bf;
  animation: ldio-4ombiim29sv 1.7543859649122806s linear infinite;
}.ldio-4ombiim29sv div:nth-child(1) > div {
  left: 74px;
  top: 44px;
  animation-delay: -1.5350877192982455s;
}
.ldio-4ombiim29sv > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 80px 50px;
}.ldio-4ombiim29sv div:nth-child(2) > div {
  left: 65px;
  top: 65px;
  animation-delay: -1.3157894736842104s;
}
.ldio-4ombiim29sv > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 71px 71px;
}.ldio-4ombiim29sv div:nth-child(3) > div {
  left: 44px;
  top: 74px;
  animation-delay: -1.0964912280701753s;
}
.ldio-4ombiim29sv > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 50px 80px;
}.ldio-4ombiim29sv div:nth-child(4) > div {
  left: 23px;
  top: 65px;
  animation-delay: -0.8771929824561403s;
}
.ldio-4ombiim29sv > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 29px 71px;
}.ldio-4ombiim29sv div:nth-child(5) > div {
  left: 14px;
  top: 44px;
  animation-delay: -0.6578947368421052s;
}
.ldio-4ombiim29sv > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 20px 50px;
}.ldio-4ombiim29sv div:nth-child(6) > div {
  left: 23px;
  top: 23px;
  animation-delay: -0.43859649122807015s;
}
.ldio-4ombiim29sv > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 29px 29px;
}.ldio-4ombiim29sv div:nth-child(7) > div {
  left: 44px;
  top: 14px;
  animation-delay: -0.21929824561403508s;
}
.ldio-4ombiim29sv > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 50px 20px;
}.ldio-4ombiim29sv div:nth-child(8) > div {
  left: 65px;
  top: 23px;
  animation-delay: 0s;
}
.ldio-4ombiim29sv > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 71px 29px;
}
.loadingio-spinner-spin-jpeea6upf9 {
  width: 84px;
  height: 84px;
  @REM display: inline-block;
  overflow: hidden;
  background: #ffffff;
  margin: 0 auto;
}
.ldio-4ombiim29sv {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.84);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-4ombiim29sv div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
